import os
from jinja2 import Environment

rst_reserved_words = []


def titleize( word, char='=' ):
  return char * len( word )


def table( data_list, header_list ):
  col_count = len( header_list )
  col_width_list = [ len( i ) for i in header_list ]
  if data_list:
    for x in range( 0, col_count ):
      col_width_list[x] = max( col_width_list[x], *[ len( i[x] ) for i in data_list ] )

  result = ''
  result += '+-' + '-+-'.join( [ '-' * i for i in col_width_list ] ) + '-+\n'
  result += '| ' + ' | '.join( [ header_list[i] + ( ' ' * ( col_width_list[i] - len( header_list[i] ) ) ) for i in range( 0, col_count ) ] ) + ' |\n'
  result += '+=' + '=+='.join( [ '=' * i for i in col_width_list ] ) + '=+\n'
  if data_list:
    for data in data_list:
      result += '| ' + ' | '.join( [ data[i] + ( ' ' * ( col_width_list[i] - len( data[i] ) ) ) for i in range( 0, col_count ) ] ) + ' |\n'
      result += '+-' + '-+-'.join( [ '-' * i for i in col_width_list ] ) + '-+\n'

  else:
    result += '+-' + '-+-'.join( [ '-' * i for i in col_width_list ] ) + '-+\n'

  return result + '\n'


def parm_extract( parm_list ):
  return [ ( parm[ 'name' ], parm[ 'type' ], str( parm.get( 'length', '' ) ), 'Yes' if parm.get( 'is_array', False ) else ' ', ', '.join( parm.get( 'choices', '' ) ), ', '.join( parm.get( 'allowed_schemes', '' ) ), parm.get( 'uri', '' ), parm.get( 'doc', '' ) ) for parm in parm_list ]


def field_extract( field_list ):
  return [ ( field[ 'name' ], field[ 'type' ], str( field.get( 'length', '' ) ), '' if field.get( 'default', '' ) is None else str( field.get( 'default', '' ) ), 'Yes' if field.get( 'is_array', False ) else ' ', ', '.join( field.get( 'choices', '' ) ), ', '.join( field.get( 'allowed_schemes', '' ) ), field.get( 'uri', '' ), field.get( 'doc', '' ) ) for field in field_list ]


def return_type_extract( return_type ):
  return [ ( return_type[ 'type' ], str( return_type.get( 'length', '' ) ), '' if return_type.get( 'default', '' ) is None else str( return_type.get( 'default', '' ) ), 'Yes' if return_type.get( 'is_array', False ) else ' ', ', '.join( return_type.get( 'choices', '' ) ), ', '.join( return_type.get( 'allowed_schemes', '' ) ), return_type.get( 'uri', '' ), return_type.get( 'doc', '' ) ) ]


env = Environment()
env.filters[ 'titleize' ] = titleize
env.filters[ 'table' ] = table
env.filters[ 'parm_extract' ] = parm_extract
env.filters[ 'field_extract' ] = field_extract
env.filters[ 'return_type_extract' ] = return_type_extract

header_template = env.from_string( """==========================={{ service|titleize }}
CInP API Documentation for {{ service }}
==========================={{ service|titleize }}

Automatically generated by cinp-codegen from {{ url }} at {{ timestamp }} for api version *{{ api_version }}*


""" )

ns_template = env.from_string( """Namespace - {{ name }}
============{{ name|titleize }}

URL: *{{ url }}*

API Version: *{{ api_version }}*
{% if doc %}
::

  {{ doc }}
{% endif %}

""" )

model_template = env.from_string( """Model - {{ name }}
--------{{ name|titleize( '-' ) }}

URL: *{{ url }}*
{% if id_field_name %}
Id Field: *{{id_field_name}}*{% endif %}
{% if not_allowed_verb_list %}
Not Allowed Verbs: *{% for item in not_allowed_verb_list %}{{ item }}{% if not loop.last %}, {% endif %}{% endfor %}*
{% endif %}{% if doc %}
::

  {{ doc }}
{% endif %}{% if constant_map %}
Constants
~~~~~~~~~ {% for key, value in constant_map %}
 - {{ key }}: {{ value }}{% endfor %}
{% endif %}{% if list_filter_map %}
List Filters
~~~~~~~~~~~~
{% for key, item in list_filter_map.items() %}
{{ key }}
{{ key|titleize( '^' ) }}
{% if item %}{{ item|parm_extract|table( [ 'Name', 'Type', 'Length', 'Array', 'Choices', 'Schemas', 'Model', 'Doc' ] ) }}{% endif %}{% endfor %}
{% endif %}{% if field_list %}
Fields
~~~~~~
{{ field_list|field_extract|table( [ 'Name', 'Type', 'Length', 'Default', 'Array', 'Choices', 'Schemas', 'Model', 'Doc' ] ) }}{% endif %}
""" )

action_template = env.from_string( """Action - {{ name }}
~~~~~~~~~{{ name|titleize( '~' ) }}

URL: *{{ url }}*

Static: *{% if static %}Yes{% else %}No{% endif %}*
{% if doc %}
::

  {{ doc }}
{% endif %}{% if return_type %}
Return Type
~~~~~~~~~~~
{{ return_type|return_type_extract|table( [ 'Type', 'Length', 'Array', 'Choices', 'Schemas', 'Model', 'Doc' ] ) }}{% endif %}{% if parameter_list %}
Parameters
~~~~~~~~~~
{{ parameter_list|parm_extract|table( [ 'Name', 'Type', 'Length', 'Array', 'Choices', 'Schemas', 'Model', 'Doc' ] ) }}{% endif %}

""" )


def write_model( fp, model ):
  value_map = {
                'name': model[ 'name' ],
                'url': model[ 'url' ],
                'doc': model[ 'doc' ].strip().replace( '\n', '\n  ' ),
                'constant_map': model[ 'constant_map' ],
                'list_filter_map': model[ 'list_filter_map' ],
                'field_list': model[ 'field_list' ],
                'not_allowed_verb_list': model[ 'not_allowed_verb_list' ],
                'id_field_name': model[ 'id_field_name' ],
              }

  fp.write( model_template.render( **value_map ) )
  for action in model[ 'action_list' ]:
    value_map = {
                  'name': action[ 'name' ],
                  'url': action[ 'url' ],
                  'static': action[ 'static' ],
                  'doc': action.get( 'doc', '' ).strip().replace( '\n', '\n  ' ),
                  'return_type': action.get( 'return_type', {} ),
                  'parameter_list': action.get( 'parameter_list', [] )
                }
    fp.write( action_template.render( **value_map ) )


def write_namespace( fp, namespace ):
  value_map = {
                'name': namespace[ 'name' ],
                'url': namespace[ 'url' ],
                'doc': namespace.get( 'doc', '' ).strip().replace( '\n', '\n  ' ),
                'api_version': namespace[ 'api_version' ]
              }
  fp.write( ns_template.render( **value_map ) )

  for model in namespace[ 'model_list' ]:
    write_model( fp, model )

  for child in namespace[ 'namespace_list' ]:
    write_namespace( fp, child )


def rst_render_func( wrk_dir, header_map, root ):
  header_map[ 'api_version' ] = root[ 'api_version' ]

  root[ 'name' ] = '(root)'

  with open( os.path.join( wrk_dir, 'api.rst' ), 'w' ) as fp:
    fp.write( header_template.render( **header_map ) )
    write_namespace( fp, root )
